version: '3.8'
services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE
      KAFKA_LISTENERS: INSIDE://kafka:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "Test Cluster"
      CASSANDRA_DC: "DC1"
      CASSANDRA_RACK: "Rack1"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"

  pyspark:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - PYSPARK_MASTER=spark://pyspark:7077
